version: "3.9"
services:
  mapper:
    container_name: network_overview
    build: .
    image: rjohn92/network-map:latest
    ports:
      - "${PORT}:${PORT}"
    environment:
      - HOST_IP=${HOST_IP}
      - PORT=${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "index.js"]