version: "3.9"
services:
  network-map:
    container_name: network-map
    build: .
    image: rjohn92/network-map:latest
    ports:
      - "${PORT}:${PORT}"
    environment:
      - HOST_IP=${HOST_IP}
      - PORT=${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "index.js"]

networks:
  network-map:  # Reuse the shared network created by network_overview
    external: true
